local M = {}
-- ASCII art for different operating systems
M.ascii_art = {
  ubuntu = {
    "             _,met$$$$$gg.            ",
    "          ,g$$$$$$$$$$$$$$$P.         ",
    '        ,g$$P"     """Y$$."`.         ',
    "       ,$$P'              `$$$.       ",
    "      ',$$P       ,ggs.     `$$b:     ",
    "      `d$$'     ,$P\"'   .    $$$     ",
    "       $$P      d$'     ,    $$P      ",
    "       $$:      $$.   -    ,d$$'      ",
    "       $$;      Y$b._   _,d$P'        ",
    '       Y$$.    `.`"Y$$$$P"\'          ',
    '       `$$b      "-.__                ',
    "        `Y$$                          ",
    "         `Y$$.                        ",
    "           `$$b.                      ",
    "             `Y$$b.                   ",
    '                `"Y$b._               ',
    '                    `""""             ',
  },

  arch = {
    "                   -`                 ",
    "                  .o+`                ",
    "                 `ooo/                ",
    "                `+oooo:               ",
    "               `+oooooo:              ",
    "               -+oooooo+:             ",
    "             `/:-:++oooo+:            ",
    "            `/++++/+++++++:           ",
    "           `/++++++++++++++:          ",
    "          `/+++ooooooooo+++:          ",
    "         ./ooosssso++osssssso+.       ",
    "        .oossssso-````/ossssss+`      ",
    "       -osssssso.      :ssssssso.     ",
    "      :osssssss/        osssso+++.    ",
    "     /ossssssss/        +ssssooo/-    ",
    "   `/ossssso+/:-        -:/+osssso+-  ",
    "  `+sso+:-`                 `.-/+oso: ",
    " `++:.                           `-/+/",
    " .`                                 `/",
  },

  macos = {
    "                        'c.            ",
    "                     ,xNMM.            ",
    "                   .OMMMMo             ",
    "                   OMMM0,              ",
    "         .;loddo:' loolloddol;.        ",
    "       cKMMMMMMMMMMNWMMMMMMMMMM0:      ",
    "     .KMMMMMMMMMMMMMMMMMMMMMMMWd.      ",
    "     XMMMMMMMMMMMMMMMMMMMMMMMX.        ",
    "    ;MMMMMMMMMMMMMMMMMMMMMMMM:         ",
    "    :MMMMMMMMMMMMMMMMMMMMMMMM:         ",
    "    .MMMMMMMMMMMMMMMMMMMMMMMMX.        ",
    "     kMMMMMMMMMMMMMMMMMMMMMMMMWd.      ",
    "     .XMMMMMMMMMMMMMMMMMMMMMMMMMMk     ",
    "      .XMMMMMMMMMMMMMMMMMMMMMMMMK.     ",
    "        kMMMMMMMMMMMMMMMMMMMMMMd       ",
    "         ;KMMMMMMMWXXWMMMMMMMk.        ",
    "           .cooc,.    .,coo:.          ",
  },

  linux = {
    "        #####           ",
    "       #######          ",
    "       ##O#O##          ",
    "       #######          ",
    "     ###########        ",
    "    #############       ",
    "   ###############      ",
    "   ################     ",
    "  #################     ",
    " #####################  ",
    "#####################   ",
    "######################  ",
    "#######################",
    "#######################",
    " #####################  ",
    "  ###################   ",
    "   #################    ",
    "    ###############     ",
    "     #############      ",
    "      ###########       ",
    "        #######         ",
    "         #####          ",
  },

  windows = {
    "        ,.=:!!t3Z3z.,           ",
    "       :tt:::tt333EE3           ",
    "       Et:::ztt33EEEL @Ee.,     ",
    "      ;tt:::tt333EE7 ;EEEEEEt,  ",
    "     :Et:::zt333EEQ. $EEEEEEtE@",
    "     it::::tt333EEF @EEEEEEEttE.",
    '    ;3=*^```"*4EEV :EEEEEEEtttEt',
    "    ,.=::::!t=., ` @EEEEEEtttz33QF",
    '   ;::::::::zt33)   "4EEEtttji3P*',
    "  :t::::::::tt33.:Z3z.. `` ,..g. ",
    "  i::::::::zt33F AEEEtttt::::ztF ",
    " ;:::::::::t33V ;EEEttttt::::t3  ",
    " E::::::::zt33L @EEEtttt::::z3F  ",
    '{3=*^```"*4E3) ;EEEtttt:::::tZ`  ',
    "             ` :EEEEtttt::::z7   ",
    '                 "VEzjt:;;z>*`   ',
  },

  unknown = {
    "   ?????????   ",
    " ????????????? ",
    "???????????????",
    "???????????????",
    "???????????????",
    "???????????????",
    " ????????????? ",
    "   ?????????   ",
  },
}
return M
